In [40]:
import numpy as np
import progressbar
try:  # SciPy >= 0.19
    from scipy.special import comb, logsumexp
except ImportError:
    from scipy.misc import comb, logsumexp
    
from itertools import product
import oapackage
    

    
def create_ortho(n,k,t):

    arrayclass=oapackage.arraydata_t(2, n, t, k)
    root_array=arrayclass.create_root()
    #print(root_array[5,3])
    
    return root_array

n = 16
t = 4
l = 4
k = 4
arrayclass = oapackage.arraydata_t(2, n, t, l)
print(arrayclass)
al=arrayclass.create_root()
al.showarraycompact()
# n = 10
# k = 10
# p = 0.5

# mask = np.empty((N, N))
# for i in range (N):
#     mask[i] = np.random.choice(a=[False, True], size=N, p=[p, 1-p])            
#     print(mask[i]) 
mask=np.array(al)

arrayclass: N 16, k 4, strength 4, s {2,2,2,2}, order 0
0000
0001
0010
0011
0100
0101
0110
0111
1000
1001
1010
1011
1100
1101
1110
1111


In [41]:
# t=2
# l=2

comb_value=comb(n,t)

def combinations(iterable, r):
    # combinations('ABCD', 2) --> AB AC AD BC BD CD
    # combinations(range(4), 3) --> 012 013 023 123
    pool = tuple(iterable)
    n = len(pool)
    if r > n:
        return
    indices = list(range(r))
    yield tuple(pool[i] for i in indices)
    while True:
        for i in reversed(range(r)):
            if indices[i] != i + n - r:
                break
        else:
            return
        indices[i] += 1
        for j in range(i+1, r):
            indices[j] = indices[j-1] + 1
        yield tuple(pool[i] for i in indices)
i=5
nCt=combinations(mask[i],t)
#nCt = list(nCt)
nCt = np.array(list(nCt))
print(nCt)

a=nCt
combination_index=a.dot(1 << np.arange(a.shape[-1] - 1, -1, -1))
print(combination_index)

[[0 1 0 1]]
[5]


In [42]:
comb_count = np.zeros((int(comb_value), pow(2,t)))

for i in range(0,int(comb_value)-1):
    index=int(combination_index[i])
    comb_count[i][index]=comb_count[i][index]+1
    
print(comb_count)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [125]:
def orthogonal_array(n,k,t,l):
    p = 0.5
    mask = np.empty((n, k))
    print ('Randomly generated matrix=')
    for i in range (n):
        mask[i] = np.random.choice(a=[False, True], size=k, p=[p, 1-p])
        print(mask[i])
    comb_value=comb(k,t)
    print ('Number of combinations fo choosing columns=', comb_value)
    comb_count = np.zeros((int(comb_value), pow(2,t)),dtype=np.uintc)

        
    for i in progressbar.progressbar(range(0,n)):
        nCt=combinations(mask[i],t)
        nCt = np.array(list(nCt))
        combination_index=nCt.dot(1 << np.arange(nCt.shape[-1] - 1, -1, -1))
        for j in range(0,int(comb_value)):
            index=int(combination_index[j])
            comb_count[j][index]=comb_count[j][index]+1

    print(comb_count)
    

In [127]:
orthogonal_array(100,32,4,3)

N/A% (0 of 100) |                        | Elapsed Time: 0:00:00 ETA:  --:--:--

Randomly generated matrix=
[1. 1. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 1. 1. 0.
 1. 0. 0. 0. 1. 1. 1. 1.]
[1. 0. 1. 1. 0. 0. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1. 1. 0.
 1. 1. 1. 0. 0. 1. 0. 1.]
[0. 1. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.
 1. 1. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 0. 1. 0. 1. 1.
 1. 1. 1. 1. 1. 1. 0. 1.]
[0. 0. 1. 1. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0.
 0. 1. 0. 0. 0. 0. 0. 1.]
[1. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 1. 1.
 0. 0. 1. 1. 0. 1. 1. 0.]
[1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 1. 0. 1. 1.
 1. 0. 1. 1. 0. 1. 0. 1.]
[0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0. 0.
 1. 1. 1. 1. 0. 1. 1. 0.]
[0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 0. 1. 0. 0. 1. 1.
 1. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.
 0. 0. 1.

100% (100 of 100) |######################| Elapsed Time: 0:00:46 Time:  0:00:46


[[ 3 10  7 ...  3  7  6]
 [ 8  5  3 ...  2  7  6]
 [ 5  8  5 ...  6  5  8]
 ...
 [ 7 12  5 ...  4  6  6]
 [ 3 10  6 ...  4  7 11]
 [ 5  9  7 ...  2  7 10]]
